from turtle import *
t=Turtle()
t.speed(0)
t.screen.setup(800, 800)
t.penup()
t.goto(0,-5)
t.write(0,align='right')
t.goto(0,0)
t.down()
for i in range(10):
    t.fd(10)
    t.left(90)
    t.fd(2)
    t.write(i+1)
    t.bk(4)
    t.fd(2)
    t.right(90)
t.fd(100)
t.stamp()
t.write('X')
t.bk(400)
t.fd(200)
t.left(90)
for i in range(10):
    t.fd(10)
    t.left(90)
    t.fd(2)
    t.up()
    t.goto(-4,(10*(i+1))-2)
    t.write(i+1,align='right')
    t.goto(-2,10*(i+1))
    t.down()
    t.bk(4)
    t.fd(2)
    t.right(90)
t.fd(100)
t.stamp()
t.write('Y')
t.bk(400)
t.fd(200)

print('Вас приветствует чертёжник.')
print('Эта программа может построить график квадратичной функции.')
print('Введите коэффицент a:')
a=int(input())
print('Теперь b:')
b=int(input())
print('И c:')
c=int(input())
def func(x):
    return ((a*(x**2))+(b*x)+c)*10
t.pencolor('red')
t.pensize(2)
t.up()
for x in range(10):
    y=func(x)
    t.goto(10*x,y)
    t.dot(5,'red')

t.screen.exitonclick()
t.screen.mainloop()

