from turtle import *
t=Turtle()
t.screen.setup(800, 800)
print('Вас приветствует чертёжник.')
print(
    'Если вы хотите увидеть сердце нажмите 1, если хотите увидеть гребни волны нажмите 2, если вы хотите увидеть окружность и квадрат с вписанной окружностью нажмите 3. если вы хотите увидеть окружность с красными точками по периметру нажмите 4 ')
c=int(input())
if c==1:
    t.speed(0)
    t.shape("turtle")
    t.hideturtle()
    t.screen.bgcolor("pink")
    t.pensize(2)
    t.pencolor('orange')
    t.begin_fill()
    t.fillcolor('red')
    t.left(90)
    t.circle(50, 185)
    t.fd(15)
    t.left(35)
    t.fd(150)
    t.left(100)
    t.fd(150)
    t.left(30)
    t.fd(10)
    t.circle(50, 180)
    t.end_fill()
    t.penup()
    t.goto(-55, -50)
    t.write('LOVE', False, font=('cool', 30, 'normal'))
    t.goto(-2, 2)
    t.pendown()
    t.dot(5, 'orange')
    t.shape("arrow")
    t.setheading(90)
    t.bk(10)
    t.color('black')
    t.stamp()
    t.showturtle()
elif c==2:
    t.up()
    t.goto(-450, 0)
    t.down()
    t.setheading(270)
    for i in range(5):
        t.circle(50, 180)
        t.begin_fill()
        t.circle(-50, 180)
        t.end_fill()
elif c==3:
    def sq_cr(side):
        for i in range(4):
            t.left(90)
            t.fd(side)
        t.bk(side / 2)
        t.circle(side / 2, 360)
        t.left(180)
        t.circle(side / 2, 360)
    sq_cr(250)
elif c==4:
    def circ(d, r, rBig):
        for i in range(d):
            t.circle(rBig, 360 / d)
            t.dot(r, "red")
    t.up()
    t.goto(350, 0)
    t.setheading(90)
    t.down()
    circ(45, 10, 350)
print(
    'Если вы хоите стереть рисунок введите 1, если хотите стереть рисунок и переместить черепашку в центр введите 2, если нет, то введите 0  ')
n = int(input())
if n == 1:
    t.clear()
    t.screen.bgcolor("white")
    t.hideturtle()
elif n == 2:
    t.reset()
    t.screen.bgcolor("white")
    t.hideturtle()
t.screen.exitonclick()
t.screen.mainloop()
